# xcp_header.py

# Standard Commands
CC_CONNECT = 0xFF
CC_DISCONNECT = 0xFE
CC_GET_STATUS = 0xFD
CC_SYNCH = 0xFC

CC_GET_COMM_MODE_INFO = 0xFB
CC_GET_ID = 0xFA
CC_SET_REQUEST = 0xF9
CC_GET_SEED = 0xF8
CC_UNLOCK = 0xF7
CC_SET_MTA = 0xF6
CC_UPLOAD = 0xF5
CC_SHORT_UPLOAD = 0xF4
CC_BUILD_CHECKSUM = 0xF3

CC_TRANSPORT_LAYER_CMD = 0xF2
CC_USER_CMD = 0xF1


# Calibration Commands
CC_DOWNLOAD = 0xF0
CC_DOWNLOAD_NEXT = 0xEF
CC_DOWNLOAD_MAX = 0xEE
CC_SHORT_DOWNLOAD = 0xED
CC_MODIFY_BITS = 0xEC

# Page switching Commands (PAG) 
CC_SET_CAL_PAGE = 0xEB
CC_GET_CAL_PAGE = 0xEA
CC_GET_PAG_PROCESSOR_INFO = 0xE9
CC_GET_SEGMENT_INFO = 0xE8
CC_GET_PAGE_INFO = 0xE7
CC_SET_SEGMENT_MODE = 0xE6
CC_GET_SEGMENT_MODE = 0xE5
CC_COPY_CAL_PAGE = 0xE4